### ISSUE TITLE
tar with dereference to avoid symlinks of assets:install

### ISSUE THREAD

**Issue by AxxL** [mapbender/docker-build#4]
Assets:install is called with symlinks.

Create the tar with the dereference flag.

ftp://ftp.gnu.org/old-gnu/Manuals/tar/html_node/tar_115.html

**Comment by AxxL** [comment]
Well, let's say tar and tar.gz is for linux (symlinks) and zip is for windows (no symlinks)

**Comment by eSlider** [comment]
Now (https://github.com/mapbender/mapbender-starter/commit/6c9175e812c2f53f5460afeb6d57fecba6228838) Mapbender provide native building zip and tarball packets with composer:
```sh 
cd application
php bin/composer build zip
php bin/composer build tar.gz```
